### ISSUE TITLE
Class 'Voidfire \ Calendar \ Models \ Event' not found

### ISSUE THREAD

**Issue by Drenoxt** [voidfire/calendar#1]
Hi, I followed the instructions step by step, but despite everything I've tried, I still see 
Facade \ Ignition \ Exceptions \ ViewException
Class 'Voidfire \ Calendar \ Models \ Event' not found
I've tried creating the model and the controller, but whatever I try to appear will be "A composer dependency is missing"

**Comment by voidfire** [comment]
Seems like the package's Model namespace was wrong.. I fixed it now you can pull the package again  and it should work.. 
you can check last commit for the change.
