### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [voidfire/calendar#3]
Nova packages site seems to have marked this project as abandoned. Is this package still being maintained?

**Comment by voidfire** [comment]
It is

**Comment by voidfire** [comment]
I have no idea why it is being marked as abandoned, I made a tag release maybe that's what they check?

**Comment by abishekrsrikaanth** [comment]
Thanks, I have a few questions regarding the workings and features of this package on a new issue. Could you please look into it. Closing this for now.
